### ISSUE TITLE
Additional argument

### ISSUE THREAD

**Issue by cielavenir** [CheckiO-Missions/checkio-task-word-pattern#1]
# https://github.com/Checkio-Game-Missions/checkio-empire-structure-pattern does not accept issues? bah

In tests.py in empire mission, pattern_level is 2-4, which is inconsistent with additional.md, which uses 1-3.

**Comment by Bryukh** [comment]
Thanks I will fix it. About issues - it need to be on handly :-(

**Comment by Bryukh** [comment]
Fixed.
